//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BorrowHistory
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Member ID is required.")]
        public int MemberId { get; set; }

        [Required(ErrorMessage = "Book ID is required.")]
        public int BookId { get; set; }

        public Nullable<System.DateTime> BorrowedAt { get; set; }
        public Nullable<System.DateTime> ReturnedAt { get; set; }
        public bool ReturnRequested { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
