// <auto-generated />
namespace LifeinnovirorMentalHealthConsultency.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class patientTableChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(patientTableChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "202507221644339_patientTableChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
